#!/bin/sh
# Gradle wrapper script
# This downloads the gradle wrapper if missing

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

GRADLE_DIST_URL="https://services.gradle.org/distributions/gradle-8.2-bin.zip"
GRADLE_HOME="$HOME/.gradle/wrapper/dists/gradle-8.2-bin"

# Download and extract gradle if needed
if [ ! -d "$GRADLE_HOME/gradle-8.2" ]; then
    echo "Downloading Gradle 8.2..."
    mkdir -p "$GRADLE_HOME"
    curl -L -o "$GRADLE_HOME/gradle-8.2-bin.zip" "$GRADLE_DIST_URL"
    cd "$GRADLE_HOME"
    unzip -q gradle-8.2-bin.zip
    rm gradle-8.2-bin.zip
    cd "$SAVED"
fi

# Set JAVA_HOME if not set
if [ -z "$JAVA_HOME" ]; then
    JAVACMD="java"
else
    JAVACMD="$JAVA_HOME/bin/java"
fi

# Run gradle
exec "$GRADLE_HOME/gradle-8.2/bin/gradle" "$@"
